### ISSUE TITLE
releases gone?

### ISSUE THREAD

**Issue by IzzySoft** [MrRar/gps_locker#1]
It seems like you have removed the release(s) and the attached APK(s). Will they come back at some point?

**Comment by MrRar** [comment]
I removed it as part of trying to add this app to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14862

Honestly I didn't expect anyone to notice that it was gone. I think it should be easy enough to put back. Let me give it a try...

**Comment by IzzySoft** [comment]
> I removed it as part of trying to add this app to F-Droid

F-Droid would ask you for those even when trying to establish reproducible builds. And your app [is already in my repo](https://apt.izzysoft.de/packages/com.github.mrrar.gps_lock/) since 2023-07-07 – which is how I noticed (my update checker complained) :wink:

> alright the old release is back now

Thanks!

> Also the APK will be signed differently.

The one at releases, or the one at F-Droid? If reproducible builds are established, F-Droid would ship the APK you signed (provided verification succeeds of course).

**Comment by MrRar** [comment]
> The one at releases, or the one at F-Droid? If reproducible builds are established, F-Droid would ship the APK you signed (provided verification succeeds of course).

I meant the releases on F-Droid. For F-Droid to use my signed APK, I think I need to specify a download URL and probably some other things as well. I don't see much of an advantage to putting APKs signed by me on F-Droid. The problem with having APKs with different signatures on F-Droid vs. Github releases is that updates won't work if the user switches where they get updates from. I don't see this app getting a lot of updates so I don't think it's much of a problem.

**Comment by IzzySoft** [comment]
> For F-Droid to use my signed APK, I think I need to specify a download URL

Yes. And that needs to be built from the very same commit the tag points to. Then reproducible build tools will be used to match their build and yours; if those confirm, your APK will be taken, else the build will be declared "failed". There might be some adjustments to be made initially to make that succeed.

> I don't see much of an advantage to putting APKs signed by me on F-Droid.

1. double-trust: you approved, F-Droid approved.
2. seamless switching for folks getting your app from different places (e.g. had it installed from PlayStore but want to cut their Google ties and get it from F-Droid now
3. a chance to get out (security) updates fast when needed (F-Droid installs can be updated with APKs you provide directly

> Github releases is that updates won't work if the user switches where they get updates from.

Not if F-Droid uses the very same :wink:

**Comment by MrRar** [comment]
> > For F-Droid to use my signed APK, I think I need to specify a download URL
> 
> Yes. And that needs to be built from the very same commit the tag points to. Then reproducible build tools will be used to match their build and yours; if those confirm, your APK will be taken, else the build will be declared "failed". There might be some adjustments to be made initially to make that succeed.
> 
> > I don't see much of an advantage to putting APKs signed by me on F-Droid.
> 
>     1. double-trust: you approved, F-Droid approved.
> 
>     2. seamless switching for folks getting your app from different places (e.g. had it installed from PlayStore but want to cut their Google ties and get it from F-Droid now
> 
>     3. a chance to get out (security) updates fast when needed (F-Droid installs can be updated with APKs you provide directly
> 
> 
> > Github releases is that updates won't work if the user switches where they get updates from.
> 
> Not if F-Droid uses the very same 😉

OK I did it: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14862/diffs?commit_id=fe083ef14e7b5235b2cee885d8d5efaf0f81a2ea
I guess I did it correctly. I `grep -r`'ed fdroiddata and found a bunch of apps that are doing the same thing.

I also added a new release for 0.1.1 which is exactly 2 bytes smaller than the old release for whatever reason.

**Comment by IzzySoft** [comment]
The lines look correct, just the linter will complain they are in the "wrong place" (take a look where the other YAML files have it). But you'll be helped there with it. Thanks!

**Comment by IzzySoft** [comment]
Now that your app is available at F-Droid, I see you've added their badge. Congrats first! But do you want me to remove it from IoD then (your app is [still listed here](https://apt.izzysoft.de/packages/com.github.mrrar.gps_lock/)? I'd happily keep it there and offer you to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to add here as well, @MrRar – what do you say? Always good to have options :wink:

**Comment by MrRar** [comment]
> Now that your app is available at F-Droid, I see you've added their badge. Congrats first! But do you want me to remove it from IoD then (your app is [still listed here](https://apt.izzysoft.de/packages/com.github.mrrar.gps_lock/)? I'd happily keep it there and offer you to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to add here as well, @MrRar – what do you say? Always good to have options 😉

Thanks! I'd recommend removing the old version with a different app id (com.github.mrrar.gps_lock). I'm cool with leaving the new version on IoD and I've added a button for it on the readme now.

**Comment by IzzySoft** [comment]
> I'd recommend removing the old version with a different app id (com.github.mrrar.gps_lock)

Yes, that was planned anyhow. From the MaintainerNotes on that one:

```yaml
MaintainerNotes:
  AppAdded: 2023-07-07
  Todo: 2024-07-01 remove as package was renamed to com.github.mrrar.gps_locker
```

Intention was to give people a hint and time to switch. I just saw I forgot to add the usual note to the app description – done that now:

```html
<p><b>Note:</b> this app is <a href='https://apt.izzysoft.de/packages/com.github.mrrar.gps_locker'>continued using a different name</a>, please switch to the new app!</p>
```

> I'm cool with leaving the new version on IoD and I've added a button for it on the readme now.

Wonderful! Then I'm very cool to keep it and just marked it accordingly:

```yaml
  DoubleList: keep
  DoubleListRef: https://github.com/MrRar/gps_locker/issues/1#issuecomment-2170465544
```

The corresponding hint should show up on the repo browser with the next sync then:

![image](https://github.com/MrRar/gps_locker/assets/6781438/0331e480-f3e0-4b9d-8b2a-16fa12037774)

Thanks a lot – also for adding the badge :star_struck:
